/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const weatherDashboard: string;
const header: string;
const lastRefresh: string;
const location: string;
const currentDate: string;
const todayContainer: string;
const currentTemperature: string;
const currentIcon: string;
const currentTemp: string;
const temperatureUnit: string;
const feelsLike: string;
const dataPoints: string;
const dataPoint: string;
const dataPointImgContainer: string;
const dataPointIcon: string;
const dataPointData: string;
const dataPointLabel: string;
const dataPointMeasurement: string;
const dataPointUnit: string;
const forecast: string;
const forecastDay: string;
const forecastDayName: string;
const forecastIcon: string;
const forecastTemps: string;
const low: string;
const high: string;
const currentWeather: string;
const chartContainer: string;
const separator: string;
const moonPhaseIcon: string;
const moonPhaseContainer: string;
const container: string;
const rowContainer: string;
const columnContainer: string;
const errorMessage: string;

export {
	header,
	location,
	forecast,
	low,
	high,
	separator,
	container
};

export default {
	"weather-dashboard": weatherDashboard,
	header,
	"last-refresh": lastRefresh,
	location,
	"current-date": currentDate,
	"today-container": todayContainer,
	"current-temperature": currentTemperature,
	"current-icon": currentIcon,
	"current-temp": currentTemp,
	"temperature-unit": temperatureUnit,
	"feels-like": feelsLike,
	"data-points": dataPoints,
	"data-point": dataPoint,
	"data-point-img-container": dataPointImgContainer,
	"data-point-icon": dataPointIcon,
	"data-point-data": dataPointData,
	"data-point-label": dataPointLabel,
	"data-point-measurement": dataPointMeasurement,
	"data-point-unit": dataPointUnit,
	forecast,
	"forecast-day": forecastDay,
	"forecast-day-name": forecastDayName,
	"forecast-icon": forecastIcon,
	"forecast-temps": forecastTemps,
	low,
	high,
	"current-weather": currentWeather,
	"chart-container": chartContainer,
	separator,
	"moon-phase-icon": moonPhaseIcon,
	"moon-phase-container": moonPhaseContainer,
	container,
	"row-container": rowContainer,
	"column-container": columnContainer,
	"error-message": errorMessage
};
