/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const weatherDashboard: string;
declare const header: string;
declare const lastRefresh: string;
declare const location: string;
declare const currentDate: string;
declare const todayContainer: string;
declare const currentTemperature: string;
declare const currentIcon: string;
declare const currentTemp: string;
declare const temperatureUnit: string;
declare const feelsLike: string;
declare const dataPoints: string;
declare const dataPoint: string;
declare const dataPointImgContainer: string;
declare const dataPointIcon: string;
declare const dataPointData: string;
declare const dataPointLabel: string;
declare const dataPointMeasurement: string;
declare const dataPointUnit: string;
declare const forecast: string;
declare const forecastDay: string;
declare const forecastDayName: string;
declare const forecastIcon: string;
declare const forecastTemps: string;
declare const low: string;
declare const high: string;
declare const currentWeather: string;
declare const chartContainer: string;
declare const separator: string;
declare const moonPhaseIcon: string;
declare const moonPhaseContainer: string;
declare const container: string;
declare const rowContainer: string;
declare const columnContainer: string;
declare const errorMessage: string;

export {
	header,
	location,
	forecast,
	low,
	high,
	separator,
	container
};

declare const __default_export__: {
	"weather-dashboard": typeof weatherDashboard;
	header: typeof header;
	"last-refresh": typeof lastRefresh;
	location: typeof location;
	"current-date": typeof currentDate;
	"today-container": typeof todayContainer;
	"current-temperature": typeof currentTemperature;
	"current-icon": typeof currentIcon;
	"current-temp": typeof currentTemp;
	"temperature-unit": typeof temperatureUnit;
	"feels-like": typeof feelsLike;
	"data-points": typeof dataPoints;
	"data-point": typeof dataPoint;
	"data-point-img-container": typeof dataPointImgContainer;
	"data-point-icon": typeof dataPointIcon;
	"data-point-data": typeof dataPointData;
	"data-point-label": typeof dataPointLabel;
	"data-point-measurement": typeof dataPointMeasurement;
	"data-point-unit": typeof dataPointUnit;
	forecast: typeof forecast;
	"forecast-day": typeof forecastDay;
	"forecast-day-name": typeof forecastDayName;
	"forecast-icon": typeof forecastIcon;
	"forecast-temps": typeof forecastTemps;
	low: typeof low;
	high: typeof high;
	"current-weather": typeof currentWeather;
	"chart-container": typeof chartContainer;
	separator: typeof separator;
	"moon-phase-icon": typeof moonPhaseIcon;
	"moon-phase-container": typeof moonPhaseContainer;
	container: typeof container;
	"row-container": typeof rowContainer;
	"column-container": typeof columnContainer;
	"error-message": typeof errorMessage;
};
export default __default_export__;
