[project]
name = "weather-dash"
version = "0.1.7"
description = "A dashboard for weather display on an ePaper display."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]==0.141.1",
    "pillow==12.3.0",
    "playwright==1.58.0",
    "prometheus-client==0.22.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
hello = "weather_dash:hello"

[tool.uv]
python-downloads = "automatic"

[dependency-groups]
dev = [
    "ruff==0.13.0",
    "fastapi-cli==0.0.32",
    "pytest==9.0.3",
    "httpx==0.28.1",
]
